spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: 'true'
  session:
    store-type: jdbc
  jpa:
    show-sql: 'true'
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MySQL5InnoDBDialect'
  profiles:
    include: 'oauth'
  mustache:
    cache: 'false'
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: metrics,prometheus

